title: Save a dog
email: birdjull@gmail.com
description: This is an idea to fulfil more than one life at a time!
destination: docs
baseurl: "" # the subpath of your site, e.g. /blog
#baseurl: "/CSS-Advanced-course" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: birdjull
github_username:  birdjull
exclude: [_assets, node_modules, .gitignore, package.json, package-lock.json, Gemfile, Gemfile.lock, gulpfile.js, README.md]
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed